### PR TITLE
Minor clarity/wording changes to README

### PR DESCRIPTION
**Pull request by flowerhack**
Hello!  Thanks for the lovely library.

I found a couple places in the README where the wording/punctuation could help make things a little more clear, so that's the contents of this (small) pull request.  Hope this is helpful!

### CODE REVIEW

**Comment by andre-merzky** [comment]
Hey @flowerhack, 

this repo has been silent for quite a while, and we thus created a fork at https://github.com/diamondman/bitarray/.   

If you are interested, please feel free to transplant your pull request to the forked repo, we would be very happy to begin the code review and merge into bitarray before pushing out a new release.  If you do not have the time to do so, we would kindly ask your permission to do the PR transfer our-self.  If you could ping back in the next couple of days, one way or the other, that would be great.

Many thanks!

**Comment by flowerhack** [comment]
Feel free to do the PR transfer yourselves; it was a pretty minor change anyway :)  Best of luck y'all!

**Comment by andre-merzky** [comment]
We'll do that - thanks, and also best wishes :)

**Comment by diamondman** [comment]
https://github.com/diamondman/bitarray/pull/11

**Comment by ilanschnell** [comment]
Thanks for this PR!

**Pull request merged**
