### PR TITLE
Use Py_SET_TYPE() and Py_SET_SIZE() for Python 3.10

### PR DESCRIPTION
**Pull request by vstinner**
Python 3.10 requires to use Py_SET_TYPE() and Py_SET_SIZE() functions
to set an object type or size.

Add a copy of the compatibility pythoncapi_compat.h header file which
provides Py_SET_TYPE() and Py_SET_SIZE() to old Python versions:
these functions were added to Python 3.9.

### CODE REVIEW

**Comment by vstinner** [comment]
> Python 3.10 requires to use Py_SET_TYPE() and Py_SET_SIZE() functions
> to set an object type or size.

See https://bugs.python.org/issue39573#msg381365 for the context: the incompatible Python 3.10 change was reverted to give time to C extension modules maintainers to port their extension. So here is such change to support Python 3.10 without losing support for old Python versions.

See also https://github.com/pythoncapi/pythoncapi_compat : I used upgrade_python_capi.py script to create this PR, and copied the pythoncapi_compat.h header file from there.

**Comment by vstinner** [comment]
I ran manually the test suite with my patch and it pass on Fedora 33 with Python 3.10.0a2:

```
python3.10 -m venv ENV
ENV/bin/python setup.py install
ENV/bin/python bitarray/test_bitarray.py 
```

**Comment by vstinner** [comment]
Without this change, it was not possible to build bitarray on Python 3.10.0a2 (again, the C API incompatible change was reverted in Python 3.10.a3).

**Comment by ilanschnell** [comment]
Thank you for this PR!  I've tested master with the 3.10.a3 release (which reverted this incompatible change), and all works fine.  Is this the incompatible C API change expected to be added again in the 3.10 final release?

**Comment by vstinner** [comment]
As I wrote, the change has been reverted in Python 3.10a3, but it may be done again in a future Python version.

**Comment by vstinner** [comment]
See Py_TYPE() documentation:
> The Py_SET_SIZE() function must be used to set an object size.

https://docs.python.org/dev/c-api/structures.html#c.Py_SIZE

**Comment by vstinner** [comment]
Thanks :-)

**Pull request merged**
