### PR TITLE
speed up repeat()

### PR DESCRIPTION
**Pull request by danielg1111**
This PR makes `repeat()` much faster when `nbits` is not a large multiple of 8.  It can provide speedups around 100x in many cases, and around 1000x for 1 or 2 bits.

It is tangentially related to https://github.com/ilanschnell/bitarray/issues/132.

 The current implementation of `repeat()` is already very efficient when`nbits` is a large multiple of 8; This optimization makes it as efficient in many more cases by doubling the number of bits copied at once until it is a large multiple of 8.  This makes it possible for `copy_n()` to efficiently use `memmove()` instead of copying each bit individually.

When `nbits` is a large multiple of 8, the performance is essentially the same as the current version.

Here are some timings with and without the optimization: 

```python
%timeit bitarray('1' * 7) * 10 ** 8
1.11 s ± 2.82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)       # original version
7.39 ms ± 42 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)     # optimized version

%timeit bitarray('10') * 10 ** 8
453 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)       # original version
610 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)   # optimized version

%timeit bitarray('1') * 10 ** 8
322 ms ± 540 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)        # original version
187 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # optimized version

%timeit bitarray('1' * 8) * 10 ** 8
520 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)       # original version
9.26 ms ± 50.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)   # optimized version  

# current implementation is already fast in this case
%timeit bitarray('1' * 8) * (10 ** 4) * (10 ** 4)  
8.57 ms ± 31.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)   # original version
8.71 ms ± 27.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)   # optimized version

```

### CODE REVIEW

**Comment by ilanschnell** [comment]
Thank you for this PR!  I think it can be simplified.  Why the `(bits_to_copy % 8 != 0 || bits_to_copy < 10000)` part?  One can simply keep doubling until half the final size is reached and then copy the remaining part.  Something like:
```
    Py_ssize_t k = nbits;
    while (k <= n * nbits / 2) {
        copy_n(self, k, self, 0, k);
        k *= 2;
    }
    copy_n(self, k, self, 0, nbits * n - k);
```

**Comment by danielg1111** [comment]
Yes, it can be simplified, although I suspect the simplification would make it somewhat slower (at least it did when I tried something similar).  My theory is that the upper limit on the size tends to improve performance by keeping it small enough to fit in cache.

**Comment by ilanschnell** [comment]
Ah, thank you for the explanation.  I didn't think about the cache size.  I'll merge it now, but probably do the simplification (after some measurements).  The speedup will still be very significant, and I'd rather not bake assumptions (like the cache size) into the code.  Thanks again!

**Comment by ilanschnell** [comment]
I remove the "cache optimization" for the sake of simplicity.  On my machine:
```
%timeit bitarray('1') * 10 ** 9
24.9 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # without cache optimization
24.1 ms ± 128 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # this PR
4.96 s ± 154 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # original version
```

**Comment by danielg1111** [comment]
Interesting.  Here's the same benchmark on my machine with and without the attempt at cache optimization:
```
%timeit bitarray('1') * 10 ** 9
16.1 ms ± 75.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)  # without cache optimization
11.3 ms ± 37.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)  # this PR 
```
I figured 10,000 bits would be small enough to fit in cache on basically any computer and have similar results, but I guess not.  Or the speedup could have been from something other than caching.

**Comment by ilanschnell** [comment]
It also depend on how the string library function `memmove()` is implemented, because this is where all the work is happening.

It also just occurred to me that one could do:
```
    while (k <= self->nbits / 2) {  /* double copies */
        if (k == 8) {
            char c = self->ob_item[0];
            memset(self->ob_item, c, (size_t) Py_SIZE(self));
            return 0;
        }
        copy_n(self, k, self, 0, k);
        k *= 2;
    }
```
That is, when we're 8 bits use `memset()`.  However, this will only bring a speedup for bitarrays of size `1`, `2`, `4` and `8`, and the speedup is not that much:
```
%timeit bitarray('1') * 10 ** 9
20.4 ms ± 184 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # with memset
24.9 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # current version
```

**Pull request merged**
