### PR TITLE
add optional pos parameter to start search from  

### PR DESCRIPTION
**Pull request by andre-merzky**
This change is backward compatible.  It adds an additional `int` (or rather `ssize_t` typed) pos parameter to `ba.search()`, and the search is started from that position on.  That significantly improves runtime for consecutive searches in large bitarrays.  In my specific use case of searching 1k long, distinct patterns 1M times in a 16MBit array, the time reduced from 80 seconds to 0.5 seconds.

### CODE REVIEW

**Comment by andre-merzky** [comment]
ping - is this repo still active?

**Comment by diamondman** [comment]
@andre-merzky I do not know. The PRs are stacking up. Wondering if most work should be done on a fork.

**Comment by andre-merzky** [comment]
Yeah, probably makes sense...  Are you volunteering? :)  If not, I guess I can maintain a fork for some time, as our group will be using that module for a while...

**Comment by diamondman** [comment]
I actually would be fine maintaining a new fork and pullin in all the pull requests. But we would need a new pypi repository name. I guess a boring bitarray1 would work fine.

**Comment by andre-merzky** [comment]
> I actually would be fine maintaining a new fork and pulling in all the pull requests.

great!  Happy to help with code reviews...

> But we would need a new pypi repository name. I guess a boring bitarray1 would work fine.

Yeah, I don't care about the name either...

Thanks!

**Comment by diamondman** [comment]
Sorry for the week delay. Interviews and presentations. 
I forked the repo. I can make the necessary changed in it to allow us to put it in a different pypi package, and to add CI tests, 
It sounds great to have help reviewing the PRs. Give me a moment to set up the new stuff.

**Comment by diamondman** [comment]
@andre-merzky I would like to move the discussion of how we can breathe new life into this project to my fork. https://github.com/diamondman/bitarray/issues/1

**Comment by diamondman** [comment]
https://github.com/diamondman/bitarray/pull/3

**Pull request closed without merging**
