### PR TITLE
update code to py3.9 syntaxt using pyugrade

### PR DESCRIPTION
**Pull request by kloczek**
Use pyupgrade --py39 to update code to py3.9.

### CODE REVIEW

**Comment by ilanschnell** [comment]
Thank you for your PR.  However, bitarray still supports Python 2.7 and 3.5+ and many of the changes are incompatible with Python 2.

**Comment by kloczek** [comment]
FYI: last python 2.x has been EOSed (End Of Service) .. +4 years ago (January 1, 2020).
Python 3.7.x has been EOSed in June 27 2023.
Python 3.8 will be EOSed in October 2024 .. however today it is REALLY hard to form larger python modules set if it is not supports at least python 3.9.
In my distribution I have +1.28k python modules packaged as rpm packages and recently I was really forced to move to 3.9 because Gnome, mesa, systemd and maaaany more other software which only uses python as scripting language requires AT LEAST python 3.9 (in that 1.28k population of the modules at least 7-8% maintainers already moved to python >=3.9 and are refusing to maintain anything new for 3.8). Two weeks ago in the same population appeared  one module which requires python >=3.10.

Normal/common practice amongst python modules maintainers is just announce that "version X.X it is last version which supports (for example) python 3.7" and it will be no more updates for that version.

**Comment by eli-schwartz** [comment]
> Python 3.8 will be EOSed in October 2024 .. however today it is REALLY hard to form larger python modules set if it is not supports at least python 3.9.

You do realize that code which supports BOTH 2.7 and 3.9 will run fine for you with 3.9?

Why is this PR needed at all? Please don't do this, it's very atypical even for people building distributions.

It violates the setup.py classifiers, and it violates the README which states:

> In 2024 (probably around July), we are planning the release of bitarray 3.0. The 3.0 release will:
> 
> - Remove Python 2.7 support.

It doesn't benefit *you* to make this change, it gives people the false impression that linux distributions as a whole do this sort of totally invalid PR, and it wastes the time of maintainers.

So many examples of situations where you cause needless friction. :(

**Comment by eli-schwartz** [comment]
> Why not keep on master up-to-date code and release only some updates for older python version creating branch on top of exact tag to release new version with some critical fixes like it is done in many other projects? 🤔

Because lots of projects *don't* want to maintain backport branches since it is more work for in this case zero gain.

Why do you insist on adding additional, unreasonable support burden on upstream projects when it provides no benefit to you anyway?

> Do you know any OS distribution which is still supported and which stil uses python 2.x? 🤔

I don't see what this has to do with anything. Proof: other OS distributions which dropped support for python 2.x do NOT go around harassing upstream projects to drop python 2.x support as well.

You're very alone here, and there's a good reason for that: because what you are doing is *wrong* and *impolite*.

Please don't give other OS distributions a bad name by making upstream projects associate "OS distributions" with your behavior.

Thanks.

**Comment by kloczek** [comment]
>  Because lots of projects don't want to maintain backport branches since it is more work for in this case zero gain.

Maintaining support for different version in single source tree is more complex.

> I don't see what this has to do with anything. Proof: other OS distributions which dropped support for python 2.x do NOT go around harassing upstream projects to drop python 2.x support as well.

Did you check using any method how many people around still needs full python 2.x support? 🤔 
ATM many OS distributions python support stretches no further than (maybe) provide package with python 2.x binaries.
Many such distributions already stopped shipping even that.
Just look around and try to find ANY OS distribution (not only Linux) which still ships `bitarray` module for python 2.x.
None? 🤔 

This is not about harassing anything or anyone.
People currently may be using python 2.x only on some legacy systems which are no longer updated on regular bases.
Announcement of EOSing python 2.x has been spread ~7 years ago so people started moving away from pyton 2.x even before it has been EOSed.

Just rhetorical question: how many tickets had you in last 4 years about python 2.x? 🤔

**Comment by kitterma** [comment]
I would like to suggest that the two of you take your argument elsewhere.  This is a closed issue.

**Pull request closed without merging**
